### ISSUE TITLE
what is the PREDICTED_FOLD?

### ISSUE THREAD

**Issue by jeffryuiop** [Maluuba/frames#5]
First of all, I would like to thank you for posting this repo. I am interested in learning more about this problem.

When I wanted to run the frametracking-evaluate eval FRAMES_JSON PREDICTION_JSON FOLD, I get that the FRAMES_JSON is the original data and that the FOLD is which fold i would like to use. My question is, what .json file should I use for the PREDICTED_FOLD, and how do I get it?

**Comment by temporaer** [comment]
Hey @jeffryuiop , `PREDICTION_JSON` is the file that contains your predictions. Its format is described [in our README](https://github.com/Maluuba/frames#predictions-format).
