### ISSUE TITLE
Any plan to release the underlying database?

### ISSUE THREAD

**Issue by hugochan** [Maluuba/frames#7]
Hello,

Thank you for releasing this great dataset! I was wondering if you have any plan to release the underlying database in the future in order to advance the research on knowledge-grounded dialog systems.

Many thanks!

**Comment by singhranjodh** [comment]
+1

**Comment by singhranjodh** [comment]
Hi,
I also want to research on an end to end dialogue system which requires the database used to create the dataset. Contributors, can you please confirm if there is any plan of releasing the database?

Thanks

**Comment by temporaer** [comment]
Hey, there are no plans to release the complete database. Note, however, that for every turn, we include the database query the wizard did and the results returned. You can create _a_ database that covers all cases by creating a set of all results ever returned.
